-- CreateTable
CREATE TABLE `statement` (
    `CODSTA` INTEGER NOT NULL AUTO_INCREMENT,
    `PHOTO` BOOLEAN NOT NULL,
    `STATEMENT` VARCHAR(191) NOT NULL,
    `CREATEDBY` VARCHAR(191) NOT NULL,
    `CREATEDAT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATEDAT` DATETIME(3) NOT NULL,
    `DELETEDAT` DATETIME(3) NULL,

    PRIMARY KEY (`CODSTA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
